FROM apache/airflow:2.10.3-python3.10

USER root

# Cài Java 17 cho Spark
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless procps \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow

# Cài đặt thư viện Airflow + Spark + Postgres + AWS
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir --default-timeout=1000 -r /requirements.txt
